import { categoryNamesProps } from "@/pages/api/equipments/categoryNames";

export type itemDataProps = {
  category: categoryNamesProps["en"];
  name: string;
  maker: string;
  about: string;
  gen?: Number | "Latest version";
  variety?: string;
  owning?: Number;
};

export const itemData: itemDataProps[] = [
  {
    category: "?",
    name: "RC-704",
    maker: "National",
    about: "Clock with radio",
    gen: 1972,
  },
  {
    category: "?",
    name: "10J-U50",
    maker: "TOSHIBA",
    about: "CRT TV",
    gen: 1986,
  },
  {
    category: "?",
    name: "AQUOS LC-13C1",
    maker: "SHARP",
    about: "Analog LCD TV",
    gen: 2001,
  },
  {
    category: "?",
    name: 'STRiDA EVO 16"',
    maker: "STRiDA",
    about: "Folding bicycle",
    gen: 2019,
  },
  {
    category: "Viewing Content",
    name: 'MacBook Pro 16"',
    maker: "Apple",
    about: "Laptop",
    gen: 2019,
    variety: "Space Gray",
  },
  {
    category: "Viewing Content",
    name: 'iMac 20"',
    maker: "Apple",
    about: "Desktop PC (Chrome OS Flex installed)",
    gen: 2007,
  },
  {
    category: "Viewing Content",
    name: 'iPad Pro 12.9"',
    maker: "Apple",
    about: "Tablet",
    gen: 2020,
    variety: "Space Gray",
  },
  {
    category: "Viewing Content",
    name: "iPad mini",
    maker: "Apple",
    about: "Tablet",
    gen: 2021,
    variety: "Space Gray",
  },
  {
    category: "Viewing Content",
    name: "iPhone 14 Pro",
    maker: "Apple",
    about: "Smart phone",
    gen: 2022,
    variety: "Space Black",
  },
  {
    category: "Viewing Content",
    name: "Phone (1)",
    maker: "Nothing",
    about: "Smart phone",
    gen: 2022,
    variety: "black",
  },
  {
    category: "Viewing Content",
    name: "iPhone SE",
    maker: "Apple",
    about: "Smart phone",
    gen: 2020,
    variety: "Midnight",
  },
  {
    category: "Taking Shots",
    name: "X-S10",
    maker: "FUJIFILM",
    about: "Mirrorless single-lens camera",
    gen: 2020,
  },
  {
    category: "Taking Shots",
    name: "XF 35mm F1.4 R",
    maker: "FUJIFILM",
    about: "Lens for single-lens camera",
    gen: 2012,
  },
  {
    category: "Taking Shots",
    name: "XF 18-55mm F2.8-4 R OIS",
    maker: "FUJIFILM",
    about: "Lens for single-lens camera",
    gen: 2012,
  },
  {
    category: "Taking Shots",
    name: "Wtulens L",
    maker: "GIZMON",
    about: "Lens for single-lens camera",
    gen: 2018,
  },
  {
    category: "Taking Shots",
    name: "Action 2",
    maker: "DJI",
    about: "Action camera",
    gen: 2021,
    variety: "Dual-Screen Combo",
  },
  {
    category: "Taking Shots",
    name: "X-700",
    maker: "MINOLTA",
    about: "Film camera",
    gen: 1981,
  },
  {
    category: "Taking Shots",
    name: "X-7",
    maker: "MINOLTA",
    about: "Film camera",
    gen: 1980,
  },
  {
    category: "Taking Shots",
    name: "MD ROKKOR 50mm F1.7",
    maker: "MINOLTA",
    about: "Lens for single-lens camera",
    gen: 1979,
  },
  {
    category: "Taking Shots",
    name: "MD ZOOM 35-70mm F3.5",
    maker: "MINOLTA",
    about: "Lens for single-lens camera",
    gen: 1981,
  },
  {
    category: "Taking Shots",
    name: "MD ZOOM 75-150mm F4",
    maker: "MINOLTA",
    about: "Lens for single-lens camera",
    gen: 1981,
  },
  {
    category: "Taking Shots",
    name: "LAND 330",
    maker: "Polaroid",
    about: "Instant film camera",
    gen: 1960,
  },
  {
    category: "Taking Shots",
    name: "RSC 2",
    maker: "DJI",
    about: "Camera stabilizer for single-lens camera",
    gen: 2020,
  },
  {
    category: "Taking Shots",
    name: "OM4",
    maker: "DJI",
    about: "Camera stabilizer for smart phone",
    gen: 2020,
  },
  {
    category: "Taking Shots",
    name: "UT-3AR",
    maker: "Velbon",
    about: "Tripod",
    gen: 2019,
  },
  {
    category: "Taking Shots",
    name: "MT-03 + LH-25",
    maker: "Leofoto",
    about: "Tripod",
    gen: 2019,
  },
  {
    category: "Taking Shots",
    name: "MT-16",
    maker: "Ulanzi",
    about: "Tripod",
    gen: 2020,
  },
  {
    category: "Taking Shots",
    name: "G1S",
    maker: "Pixel",
    about: "Full-color video light",
    gen: 2020,
  },
  {
    category: "Taking Shots",
    name: "SpyderCHECKR SCK100",
    maker: "Datacolor",
    about: "Color reference tool",
    gen: 2017,
  },
  {
    category: "Taking Shots",
    name: "SR3374",
    maker: "SmallRig",
    about: "Teleprompter for tablet",
    gen: 2021,
  },
  {
    category: "Develop and Design",
    name: "Illustrator",
    maker: "Adobe",
    about: "Vector graphics editor and design program",
    gen: "Latest version",
  },
  {
    category: "Develop and Design",
    name: "XD",
    maker: "Adobe",
    about: "Vector-based user experience design tool for web apps and mobile apps",
    gen: "Latest version",
  },
  {
    category: "Develop and Design",
    name: "Premiere Pro",
    maker: "Adobe",
    about: "Timeline-based video editing software application",
    gen: "Latest version",
  },
  {
    category: "Develop and Design",
    name: "After Effects",
    maker: "Adobe",
    about: "Digital visual effects, motion graphics, and compositing application",
    gen: "Latest version",
  },
  {
    category: "Develop and Design",
    name: "Photoshop",
    maker: "Adobe",
    about: "Raster graphics editor",
    gen: "Latest version",
  },
  {
    category: "Develop and Design",
    name: "Lightroom",
    maker: "Adobe",
    about: "Creative image organization and image manipulation software",
    gen: "Latest version",
  },
  {
    category: "Develop and Design",
    name: "Visual Studio Code",
    maker: "Microsoft",
    about: "Source code editor",
    gen: "Latest version",
  },
  {
    category: "Develop and Design",
    name: "Figma",
    maker: "Figma",
    about: "Vector graphics editor and prototyping tool",
    gen: "Latest version",
  },
  {
    category: "Develop and Design",
    name: "STUDIO",
    maker: "STUDIO",
    about: "Cloud-based no code website creation tool",
    gen: "Latest version",
  },
  {
    category: "Audio",
    name: "PO-80",
    maker: "teenage engineering",
    about: "Compact and portable record cutter",
    gen: 2022,
  },
  {
    category: "Audio",
    name: "DRUMSET SESSION I",
    maker: "AKG",
    about: "Drum microphone set",
    gen: 2016,
  },
  {
    category: "Audio",
    name: "ATR2100x-USB",
    maker: "audio-technica",
    about: "USB Microphone",
    gen: 2020,
  },
  {
    category: "Audio",
    name: "QX1002USB",
    maker: "behringer",
    about: "Analog mixer with audio interface",
    gen: 2012,
  },
  {
    category: "Audio",
    name: "ATH-M40x",
    maker: "audio-technica",
    about: "Headphone",
    gen: 2014,
  },
  {
    category: "Audio",
    name: "M-1",
    maker: "teenage engineering",
    about: "Headphone",
    gen: 2019,
  },
  {
    category: "Audio",
    name: "ear (1)",
    maker: "Nothing",
    about: "True wireless earphone",
    gen: 2021,
    variety: "white",
  },
  {
    category: "Audio",
    name: "ear (1)",
    maker: "Nothing",
    about: "True wireless earphone",
    gen: 2021,
    variety: "black",
  },
  {
    category: "Audio",
    name: "Powerbeats Pro",
    maker: "Beats",
    about: "True wireless earphone",
    gen: 2020,
    variety: "black",
  },
  {
    category: "Audio",
    name: "Beats Flex",
    maker: "Beats",
    about: "Left and right integrated earphones",
    gen: 2020,
    variety: "black",
  },
  {
    category: "Music Performance",
    name: "SW108",
    maker: "ARCO",
    about: "Cajon",
  },
  {
    category: "Music Performance",
    name: "5000CJ",
    maker: "DW",
    about: "Cajon pedal",
  },
  {
    category: "Music Performance",
    name: "MUS1455M",
    maker: "Pearl",
    about: "Snare drum",
  },
  // {
  //   name: "SD1410",
  //   maker: "Foldrum",
  //   about: "Floor snare drum",
  //   variety: "Custom",
  // },
  // {
  //   name: "P-932",
  //   maker: "Pearl",
  //   about: "Longboard double bass drum pedal",
  // },
  // {
  //   name: "CC16MC-B",
  //   maker: "MEINL",
  //   about: '16" clash cymbal',
  // },
  // {
  //   name: "CC12S-B",
  //   maker: "MEINL",
  //   about: '12" splash cymbal',
  //   owning: 2,
  // },
  // {
  //   name: "PST-7 Crash",
  //   maker: "Paiste",
  //   about: '16" clash cymbal',
  // },
  // {
  //   name: "PST-7 Splash",
  //   maker: "Paiste",
  //   about: '10" splash cymbal',
  // },
  // {
  //   name: "PTM-10GH",
  //   maker: "Pearl",
  //   about: "Quickmount tambourine with brass jingles",
  // },
  {
    category: "Music Performance",
    name: "SH50",
    maker: "MEINL",
    about: "Shaker in the shape of a cajon",
    variety: "Baltic Birch",
  },
  // {
  //   name: "taktile 25",
  //   maker: "KORG",
  //   about: "USB/MIDI controller for everything from mixer control to editing software synthesizers.",
  //   gen: 2014,
  // },
  {
    category: "Music Performance",
    name: "VL-1",
    maker: "Casio",
    about: "Calculator, monophonic synthesizer, and sequencer all in one",
    gen: 1981,
  },
  // {
  //   name: "Stylophone S1",
  //   maker: "Dubreq",
  //   about: "Miniature analog stylus-operated keyboard",
  //   gen: 2007,
  // },
];
